name: ServerFeatures
version: ${project.version}
main: nl.hauntedmc.serverfeatures.ServerFeatures
description: HauntedMC Feature Framework (Platform=Paper)
author: HauntedMC
website: https://hauntedmc.nl
api-version: 1.21
softdepend: [ DataRegistry, DataProvider, packetevents, PlaceholderAPI, Essentials ]

commands:
  serverfeatures:
    description: Manage server features
    usage: /serverfeatures <subcommand>
    permission: serverfeatures.use
    permission-message: You do not have permission to use this command.

permissions:
  serverfeatures.feature.invtools.command.inventory.open.inspect:
    description: Inspect online and offline player inventories with /inv inventory open.
    default: false
  serverfeatures.feature.invtools.command.inventory.open.edit:
    description: Edit inventories opened through /inv inventory open.
    default: false
  serverfeatures.feature.invtools.command.inventory.clear:
    description: Clear online and offline player inventories with /inv inventory clear.
    default: false
  serverfeatures.feature.invtools.command.enderchest.open.inspect:
    description: Inspect online and offline player ender chests with /inv enderchest open.
    default: false
  serverfeatures.feature.invtools.command.enderchest.open.edit:
    description: Edit ender chests opened through /inv enderchest open.
    default: false
  serverfeatures.feature.invtools.command.enderchest.clear:
    description: Clear online and offline player ender chests with /inv enderchest clear.
    default: false
