<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>nl.hauntedmc.serverfeatures</groupId>
        <artifactId>serverfeatures-parent</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>serverfeatures-api</artifactId>
    <name>ServerFeatures API</name>
    <properties>
        <coverage.line.minimum>0.80</coverage.line.minimum>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Automatic-Module-Name>nl.hauntedmc.serverfeatures.api</Automatic-Module-Name>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
